title: Ada0l's blog
author:
  name: ""
  email: ""
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
   - { platform: github,         user_url: "https://github.com/ada0l" }
   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/andrey-varfolomeev-318ab9280/" }
   - { platform: telegram,       user_url: "https://t.me/x919491" }

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

header_pages:
  - about.markdown
